### ISSUE TITLE
use yarn v1 instead of npm

### ISSUE THREAD

**Issue by statikdev** [MonkeDAO/monke-dao-webapp#7]
hey monkedao web team --

thoughts on switching to `yarn` for dependency management? i am planning to switch over to `next.js` tonight and they use `yarn` by default in their templates.

the other benefit is as we build out the site some more with api functionality and possibly subsites, we can use the `yarn workspaces` feature to have common modules without needing to deploy to `npm`.

let me know your thoughts.

**Comment by jakeburden** [comment]
Works for me! There is already a `yarn.lock` in the repo, is there anything else we need to do to make the switch aside from committing to using `yarn`?

**Comment by bfriel** [comment]
I'm good with yarn!

**Comment by statikdev** [comment]
> Works for me! There is already a yarn.lock in the repo, is there anything else we need to do to make the switch aside from committing to using yarn?

it looks like `package-lock.json` accidentally got committed. so i am just removing it. :)

**Comment by statikdev** [comment]
> Works for me! There is already a `yarn.lock` in the repo, is there anything else we need to do to make the switch aside from committing to using `yarn`?

it looks like `package-lock.json` accidentally got committed. so i am just removing it. :)
